# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/billy/Documents/uwe/cans/battleship

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/billy/Documents/uwe/cans/battleship

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/billy/Documents/uwe/cans/battleship/CMakeFiles /home/billy/Documents/uwe/cans/battleship/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/billy/Documents/uwe/cans/battleship/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named battleship.exe

# Build rule for target.
battleship.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 battleship.exe
.PHONY : battleship.exe

# fast build rule for target.
battleship.exe/fast:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/build
.PHONY : battleship.exe/fast

src/bot-master.o: src/bot-master.cpp.o

.PHONY : src/bot-master.o

# target to build an object file
src/bot-master.cpp.o:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/bot-master.cpp.o
.PHONY : src/bot-master.cpp.o

src/bot-master.i: src/bot-master.cpp.i

.PHONY : src/bot-master.i

# target to preprocess a source file
src/bot-master.cpp.i:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/bot-master.cpp.i
.PHONY : src/bot-master.cpp.i

src/bot-master.s: src/bot-master.cpp.s

.PHONY : src/bot-master.s

# target to generate assembly for a file
src/bot-master.cpp.s:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/bot-master.cpp.s
.PHONY : src/bot-master.cpp.s

src/bot-zombie.o: src/bot-zombie.cpp.o

.PHONY : src/bot-zombie.o

# target to build an object file
src/bot-zombie.cpp.o:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/bot-zombie.cpp.o
.PHONY : src/bot-zombie.cpp.o

src/bot-zombie.i: src/bot-zombie.cpp.i

.PHONY : src/bot-zombie.i

# target to preprocess a source file
src/bot-zombie.cpp.i:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/bot-zombie.cpp.i
.PHONY : src/bot-zombie.cpp.i

src/bot-zombie.s: src/bot-zombie.cpp.s

.PHONY : src/bot-zombie.s

# target to generate assembly for a file
src/bot-zombie.cpp.s:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/bot-zombie.cpp.s
.PHONY : src/bot-zombie.cpp.s

src/connection.o: src/connection.cpp.o

.PHONY : src/connection.o

# target to build an object file
src/connection.cpp.o:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/connection.cpp.o
.PHONY : src/connection.cpp.o

src/connection.i: src/connection.cpp.i

.PHONY : src/connection.i

# target to preprocess a source file
src/connection.cpp.i:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/connection.cpp.i
.PHONY : src/connection.cpp.i

src/connection.s: src/connection.cpp.s

.PHONY : src/connection.s

# target to generate assembly for a file
src/connection.cpp.s:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/connection.cpp.s
.PHONY : src/connection.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/network_manager.o: src/network_manager.cpp.o

.PHONY : src/network_manager.o

# target to build an object file
src/network_manager.cpp.o:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/network_manager.cpp.o
.PHONY : src/network_manager.cpp.o

src/network_manager.i: src/network_manager.cpp.i

.PHONY : src/network_manager.i

# target to preprocess a source file
src/network_manager.cpp.i:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/network_manager.cpp.i
.PHONY : src/network_manager.cpp.i

src/network_manager.s: src/network_manager.cpp.s

.PHONY : src/network_manager.s

# target to generate assembly for a file
src/network_manager.cpp.s:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/network_manager.cpp.s
.PHONY : src/network_manager.cpp.s

src/ship.o: src/ship.cpp.o

.PHONY : src/ship.o

# target to build an object file
src/ship.cpp.o:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/ship.cpp.o
.PHONY : src/ship.cpp.o

src/ship.i: src/ship.cpp.i

.PHONY : src/ship.i

# target to preprocess a source file
src/ship.cpp.i:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/ship.cpp.i
.PHONY : src/ship.cpp.i

src/ship.s: src/ship.cpp.s

.PHONY : src/ship.s

# target to generate assembly for a file
src/ship.cpp.s:
	$(MAKE) -f CMakeFiles/battleship.exe.dir/build.make CMakeFiles/battleship.exe.dir/src/ship.cpp.s
.PHONY : src/ship.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... battleship.exe"
	@echo "... src/bot-master.o"
	@echo "... src/bot-master.i"
	@echo "... src/bot-master.s"
	@echo "... src/bot-zombie.o"
	@echo "... src/bot-zombie.i"
	@echo "... src/bot-zombie.s"
	@echo "... src/connection.o"
	@echo "... src/connection.i"
	@echo "... src/connection.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/network_manager.o"
	@echo "... src/network_manager.i"
	@echo "... src/network_manager.s"
	@echo "... src/ship.o"
	@echo "... src/ship.i"
	@echo "... src/ship.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

